language: php
php:
  - '5.6'
  - '7.0'
  - 'nightly'
  - 'hhvm'
env:
  matrix:
    - COMPOSER_ARGS="install"
    - COMPOSER_ARGS="update --prefer-lowest"
install:
  - 'composer $COMPOSER_ARGS'
  - 'sudo mysql -e "CREATE DATABASE phuria_test"'
script:
  - './vendor/bin/phpunit Tests'